version: '3.7'

services:
  server:
    command: npm start
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgres://postgres:!!!abc789@postgres:5432/fixmap
